# Generated by Django 4.1.13 on 2023-11-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_sci", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.FloatField()),
                ("Glucose", models.FloatField()),
                ("Insulin", models.FloatField()),
                ("BMI", models.FloatField()),
                ("Age", models.FloatField()),
                ("added_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
